version: '3.5'
services:
  pampam_postgres2:
    container_name: pampam_postgres2
    image: postgres:11.2
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: '250330'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - 5435:5435
  pampam_backend:
    container_name: pampam_backend
    build:
      context: .
    restart: on-failure
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - pampam_postgres2
    links:
      - pampam_postgres2